[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
cap-std = "2.0"
tokio = { version = "1.0", features = ["full"] }
wasmtime = "18.0.0"
wasmtime-wasi = "18.0.0"
dyna = { path = "../.." }
